{% set name = "fpm" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.F90  # [unix]
    sha256: d16e45b705029d6d38b0ba7cccab2b9edb48c2f29441473548b866da0389243e  # [unix]
    fn: fpm.F90  # [unix]
    folder: build/bootstrap  # [unix]
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.zip  # [unix]
    sha256: 536dec7d4502221734683b15e6ff64a6ab3f9910df122d18f851c9a68711f91f  # [unix]
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}-windows-x86_64.exe  # [win]
    sha256: 0023cc21e71d0c6715c90d0183a2b073d2d1e836a3ddee87523b31b69ceadf3c  # [win]
    fn: fpm.exe  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]


test:
  commands:
    - fpm --version

about:
  home: https://github.com/fortran-lang/fpm
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE-MIT.toml-f
    - LICENSE-Apache.toml-f
    - LICENSE.M_CLI2
  summary: Fortran package manager
  doc_url: https://fpm.fortran-lang.org
  dev_url: https://github.com/fortran-lang/fpm

extra:
  recipe-maintainers:
    - awvwgk
    - certik
